# Generated by Django 2.1.5 on 2019-02-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogJoseph', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentee',
            new_name='Person',
        ),
    ]
